version: '3.4'

services:
  partnernode:
    image: pn:pn
    build:
      context: .
      dockerfile: PartnerNode/Dockerfile
    depends_on:
      - ethereum
      - mssql
      - ipfs
    ports:
      - "8081:80"
  ethereum:
    image: pn:eth
    build:
      context: ../EthPrivateNode/
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "30303:30303"
  ipfs:
    image: pn:ipfs
    build:
      context: ../IpfsNode/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5001:5001"
      - "4001:4001"
  mssql:
    image: microsoft/mssql-server-linux
    restart: on-failure
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mssqlP@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Enterprise" 