version: '3.4'

services:
  partnernode:
    image: pn:pn
    build:
      context: .
      dockerfile: PartnerNode/Dockerfile
  ethereum:
    image: pn:eth
    build:
      context: ../EthPrivateNode/
      dockerfile: Dockerfile
  ipfs:
    image: ipfs/go-ipfs:latest
    restart: on-failure
    command: 'daemon'